---
title: "lr_on_datasets"
author: "Daniel Zoleikhaeian"
date: "2023-03-03"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading libraries
```{r}
library(plyr)
library(dplyr)
library(readxl)
library(ggplot2)
```

## Working directory
```{r}
setwd("C:/Users/danie/Documents/Joshi Lab Materials/3 Studies Dataset/Dataset Merge/012623")
```

## Loading Datasets and creating average dataset
```{r}
total_df <- read.csv('bgc_merge_cDiag123_new.csv')

# Changing La Jolla to San Diego
total_df$cLocationCity[total_df$cLocationCity == 'La Jolla'] <- 'San Diego'
# Changing Brooklyn to New York
total_df$cLocationCity[total_df$cLocationCity == 'Brooklyn'] <- 'New York'

# Removing USC/MASS
total_df <- total_df[total_df$cLocationCity != 'USC/MASS', ]

df_check_2010 <- read_xlsx('reproj_30_2010.xlsx')
df_check_2020 <- read_xlsx('reproj_30_2020.xlsx')

dem_2010 <- df_check_2010[,-1]
dem_2020 <- df_check_2020[,-1]

df_avg <- df_check_2010
df_avg[,] <- NA
df_avg$City <- NULL

for (i in 1:ncol(dem_2010)) {
  df_avg[,i] <- rowMeans(cbind(dem_2010[,i], dem_2020[,i]))
  
}

df_avg <- cbind(df_check_2010$City, df_avg)
colnames(df_avg)[1] <- 'City'


# Reformatting cities
for (i in 1:length(df_avg$City)) {
  df_avg$City[i] <- substr(df_avg$City[i], 1, unlist(gregexpr(',', df_avg$City[i]))[1] - 1)
}

df_avg$City[df_avg$City == 'Stonybrook'] <- 'Stony Brook'

# Standardizing race acronyms
colnames(df_avg)[colnames(df_avg) == 'NA'] <- 'AE'
colnames(df_avg)[colnames(df_avg) == 'NH'] <- 'Not Hispanic'
colnames(df_avg)[colnames(df_avg) == 'PI'] <- 'NH'

#View(df_avg)

# Re-run with only GPC and COGS 

# Looking only at SZSAFD
szsafd <- total_df[total_df$cDiagnosis4 == 'SZSAFD', ]
cs <- total_df[total_df$cDiagnosis4 == 'CS', ]
bad12 <- total_df[total_df$cDiagnosis4 == 'BAD12',]
mdd <- total_df[total_df$cDiagnosis4 == 'MDD', ]


# Looking at city intersection between dataset and 
# test_cities <- intersect(df_avg$City, szsafd$cLocationCity)
# test_cities
```



## Function for getting plot and lm data
```{r}

race_cities_plot_data <- function(null_df, obs_df, race_acr) {

  obs_cities <- obs_df$cLocationCity[obs_df$cRace == race_acr]

  test_cities <- intersect(null_df$City, obs_cities)

  null_race_cts <- null_df[, 1:8]

 null_race_cts <- df_avg[, 1:8]
  null_race_props <- null_race_cts

  for (i in 1:nrow(null_race_cts)) {
    city_tot <- sum(null_race_cts[i, 2:8])
    null_race_props[i, 2:8] <- null_race_cts[i,2:8] / city_tot
  }

  null_race_props <- null_race_props[null_race_props$City %in% test_cities,]
  null_race_props <- null_race_props[order(null_race_props$City), ]

  brc <- obs_df %>%
    dplyr::group_by(cRace, cLocationCity) %>%
    dplyr::summarise(total_count=n(), .groups = 'drop')

  brc <- brc[brc$cLocationCity %in% test_cities, ]

  brc <- brc[order(brc$cLocationCity), ]
  brc$Prop <- NA

  # Turning counts into proportions
  for (i in 1:length(test_cities)) {
    brc$Prop[brc$cLocationCity == test_cities[i]] <- brc$total_count[brc$cLocationCity == test_cities[i]] / sum(brc$total_count[brc$cLocationCity == test_cities[i]])
  }

  null_row <- as.data.frame(null_race_props[,c('City', race_acr)])
  obs_races <- brc[brc$cRace == race_acr, ]
  obs_prop <- obs_races$Prop

  ## Begin output variables to send to lm() and plot()
  propdif <- obs_prop - null_row[,2] ## response
  city_cts <- plyr::count(obs_df$cLocationCity)
  ct_to_plot <- city_cts$freq[city_cts$x %in% test_cities] ## predictor 1

  null_race_cts <- null_race_cts[null_race_cts$City %in% test_cities, ]
  race_of_interest_null <- null_race_cts[, colnames(null_race_cts) == race_acr] ## predictor 2

  null_race_sums <- as.data.frame(apply(null_race_cts[,-1], 1, sum)) ## predictor 3
  colnames(null_race_sums) <- 'Total City Population'

  output <- list(propdif, ct_to_plot, race_of_interest_null, null_race_sums[,1])
  names(output) <- c('Prop dif', 'city sample', 'census average race count', 'census average pop total')

  return (output)

}

race_cities_plot_data2 <- function(null_df, tot_df, disease, study, race_acr) {
  
  obs_df <- tot_df[tot_df$cStudy %in% study & tot_df$cDiagnosis4 == disease, ]
  
  obs_cities <- obs_df$cLocationCity[obs_df$cRace == race_acr]
  
  test_cities <- intersect(null_df$City, obs_cities)
  
  null_race_cts <- null_df[, 1:8]

  null_race_cts <- df_avg[, 1:8]
  null_race_props <- null_race_cts

  for (i in 1:nrow(null_race_cts)) {
    city_tot <- sum(null_race_cts[i, 2:8])
    null_race_props[i, 2:8] <- null_race_cts[i,2:8] / city_tot
  }
  null_race_props <- null_race_props[null_race_props$City %in% test_cities,]
  null_race_props <- null_race_props[order(null_race_props$City), ]
  
  brc <- obs_df %>%  
    dplyr::group_by(cRace, cLocationCity) %>%  
    dplyr::summarise(total_count=n(), .groups = 'drop')
  
  brc <- brc[brc$cLocationCity %in% test_cities, ]
  
  brc <- brc[order(brc$cLocationCity), ]
  brc$Prop <- NA
  
  # Turning counts into proportions
  for (i in 1:length(test_cities)) {
    brc$Prop[brc$cLocationCity == test_cities[i]] <- brc$total_count[brc$cLocationCity == test_cities[i]] / sum(brc$total_count[brc$cLocationCity == test_cities[i]])
  }
  
  null_row <- as.data.frame(null_race_props[,c('City', race_acr)])
  obs_races <- brc[brc$cRace == race_acr, ]
  obs_prop <- obs_races$Prop
  
  ## Begin output variables to send to lm() and plot()
  propdif <- obs_prop - null_row[,2] ## response
  city_cts <- plyr::count(obs_df$cLocationCity)
  ct_to_plot <- city_cts$freq[city_cts$x %in% test_cities] ## predictor 1
  
  null_race_cts <- null_race_cts[null_race_cts$City %in% test_cities, ]
  race_of_interest_null <- null_race_cts[, colnames(null_race_cts) == race_acr] ## predictor 2
  
  null_race_sums <- as.data.frame(apply(null_race_cts[,-1], 1, sum)) ## predictor 3
  colnames(null_race_sums) <- 'Total City Population'
  
  output <- list(propdif, ct_to_plot, race_of_interest_null, null_race_sums[,1])
  names(output) <- c('Prop dif', 'city sample', 'census average race count', 'census average pop total')
  
  return (output)
  
}

plot_race_lm <- function(data_list, race_acr, disease, study) {
  plot(log(data_list[[2]]), data_list[[1]], main = paste(disease, ': Proportion Difference by Sample Size for ', race_acr, sep = ''), xlab = 'Log(City Sample Size)', ylab = 'Proportion Difference (Observed - Census Average)' )
    text(log(data_list[[2]]), data_list[[1]], 1:length(data_list[[2]]), pos=4, offset = 0.25)

  
  city_sam_lr <- lm(data_list[[1]] ~ log(data_list[[2]]))
  abline(city_sam_lr, col = 'red', lwd = 2)
  

  # mtext(paste(study, 'Adj R-squared=', round(summary(city_sam_lr)$adj.r.squared,3)), side = 3)
  mtext(paste(paste(study, collapse='+ ' ), 'Adj R-squared=', round(summary(city_sam_lr)$adj.r.squared,3)), side = 3)
  
  if(length(data_list[[1]]) > 2) {
    plot(city_sam_lr, 1)
    plot(city_sam_lr, 4)
  }

  plot(log(data_list[[3]]), data_list[[1]], main = paste(disease, ': Proportion Difference by City Population for ', race_acr, sep = ''), xlab = paste('log(',race_acr,' population)', sep = ''), ylab = 'Proportion Difference (Observed - Census Average)' )
  text(log(data_list[[3]]), data_list[[1]], 1:length(data_list[[3]]), pos=4, offset = 0.25)


  race_total_pop_lr <- lm(data_list[[1]] ~ log(data_list[[3]]))
  abline(race_total_pop_lr, col = 'red')
  mtext(paste(paste(study, collapse='+ ' ), 'Adj R-squared=', round(summary(race_total_pop_lr)$adj.r.squared,3)), side = 3)
  
  if (length(data_list[[1]]) > 2) {
    plot(race_total_pop_lr, 1)
    plot(race_total_pop_lr, 4)
  }
  
  
  Total_city_pop <- lm(data_list[[1]] ~ log(data_list[[4]]))

  plot(log(data_list[[4]]), data_list[[1]], main = paste(disease, ': Proportion Difference in ', race_acr, ' by Total City Population', sep = ''), xlab = 'log(Total City Population)', ylab = 'Proportion Difference (Observed - Census Average)' )
    text(log(data_list[[4]]), data_list[[1]], 1:length(data_list[[4]]), pos=4, offset = 0.25)

  
  abline(Total_city_pop, col = 'red')
  mtext(paste(paste(study, collapse='+ ' ), 'Adj R-squared=', round(summary(Total_city_pop)$adj.r.squared,3)), side = 3)
  
  if (length(data_list[[1]]) > 2) {
    plot(Total_city_pop, 1)
    plot(Total_city_pop, 4)
  }
  
  return(list(city_sam_lr, race_total_pop_lr, Total_city_pop))
  
}

```


## Setting up variables to loop through
```{r}
race_acrs <- c('AA', 'AS', 'CA')
diagnoses <- c('SZSAFD', 'BAD12','CS') # MDD omitted bc data too sparse 
```

## GPC Analysis
```{r}
for (i in 1:length(diagnoses)) {
  for (j in 1:length(race_acrs)) {
    rcp_d <- race_cities_plot_data2(df_avg, total_df, diagnoses[i],'GPC', race_acrs[j])
    plot_race_lm(rcp_d, race_acrs[j], diagnoses[i], 'GPC')
  }
}
```

## COGS2 + BSNIP1 + BSNIP2 Analysis

```{r}
studies <- c('COGS2', 'BSNIP1', 'BSNIP2')
for (i in 1:length(diagnoses)) {
  for (j in 1:length(race_acrs)) {
    rcp_d <- race_cities_plot_data2(df_avg, total_df, diagnoses[i],studies, race_acrs[j])
    plot_race_lm(rcp_d, race_acrs[j], diagnoses[i], studies)
  }
}

```

## Reasons for Omission
```{r}
# No MDD in COGS2 + BSNIP1 + BSNIP2
levels(factor(mdd$cLocationCity[mdd$cStudy %in% studies]))

levels(factor(mdd$cLocationCity[mdd$cStudy %in% 'GPC' & mdd$cRace == 'AA' & mdd$cLocationCity %in% df_avg$City]))

levels(factor(mdd$cLocationCity[mdd$cStudy %in% 'GPC' & mdd$cRace == 'AS' & mdd$cLocationCity %in% df_avg$City]))

levels(factor(mdd$cLocationCity[mdd$cStudy %in% 'GPC' & mdd$cRace == 'CA' & mdd$cLocationCity %in% df_avg$City]))
```

## Additional analysis on MDD - for GPC only

```{r}
for (j in 1:length(race_acrs)) {
  rcp_d <- race_cities_plot_data2(df_avg, total_df, 'MDD','GPC', race_acrs[j])
  plot_race_lm(rcp_d, race_acrs[j], 'MDD', 'GPC')
}
```

## Aggregating GPC and COGS2

```{r}
studies2 <- c('COGS2', 'GPC')
for (i in 1:length(diagnoses)) {
  for (j in 1:length(race_acrs)) {
    rcp_d <- race_cities_plot_data2(df_avg, total_df, diagnoses[i],studies2, race_acrs[j])
    plot_race_lm(rcp_d, race_acrs[j], diagnoses[i], studies2)
  }
}
```
